// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recipe.proto

package recipe

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type IngredientInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IngredientInfo) Reset()         { *m = IngredientInfo{} }
func (m *IngredientInfo) String() string { return proto.CompactTextString(m) }
func (*IngredientInfo) ProtoMessage()    {}
func (*IngredientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{1}
}

func (m *IngredientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IngredientInfo.Unmarshal(m, b)
}
func (m *IngredientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IngredientInfo.Marshal(b, m, deterministic)
}
func (m *IngredientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IngredientInfo.Merge(m, src)
}
func (m *IngredientInfo) XXX_Size() int {
	return xxx_messageInfo_IngredientInfo.Size(m)
}
func (m *IngredientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_IngredientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_IngredientInfo proto.InternalMessageInfo

func (m *IngredientInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NewRecipe struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ingredient           *IngredientInfo `protobuf:"bytes,2,opt,name=ingredient,proto3" json:"ingredient,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NewRecipe) Reset()         { *m = NewRecipe{} }
func (m *NewRecipe) String() string { return proto.CompactTextString(m) }
func (*NewRecipe) ProtoMessage()    {}
func (*NewRecipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{2}
}

func (m *NewRecipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRecipe.Unmarshal(m, b)
}
func (m *NewRecipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRecipe.Marshal(b, m, deterministic)
}
func (m *NewRecipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRecipe.Merge(m, src)
}
func (m *NewRecipe) XXX_Size() int {
	return xxx_messageInfo_NewRecipe.Size(m)
}
func (m *NewRecipe) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRecipe.DiscardUnknown(m)
}

var xxx_messageInfo_NewRecipe proto.InternalMessageInfo

func (m *NewRecipe) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewRecipe) GetIngredient() *IngredientInfo {
	if m != nil {
		return m.Ingredient
	}
	return nil
}

type RecipeName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecipeName) Reset()         { *m = RecipeName{} }
func (m *RecipeName) String() string { return proto.CompactTextString(m) }
func (*RecipeName) ProtoMessage()    {}
func (*RecipeName) Descriptor() ([]byte, []int) {
	return fileDescriptor_952719e3f4c063a9, []int{3}
}

func (m *RecipeName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeName.Unmarshal(m, b)
}
func (m *RecipeName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeName.Marshal(b, m, deterministic)
}
func (m *RecipeName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeName.Merge(m, src)
}
func (m *RecipeName) XXX_Size() int {
	return xxx_messageInfo_RecipeName.Size(m)
}
func (m *RecipeName) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeName.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeName proto.InternalMessageInfo

func (m *RecipeName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*IngredientInfo)(nil), "IngredientInfo")
	proto.RegisterType((*NewRecipe)(nil), "NewRecipe")
	proto.RegisterType((*RecipeName)(nil), "RecipeName")
}

func init() { proto.RegisterFile("recipe.proto", fileDescriptor_952719e3f4c063a9) }

var fileDescriptor_952719e3f4c063a9 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x51, 0x4b, 0x86, 0x30,
	0x14, 0x86, 0xb3, 0xaf, 0xbe, 0xda, 0x31, 0x12, 0x76, 0x35, 0xba, 0x08, 0x19, 0x5d, 0x08, 0xc1,
	0x02, 0xfb, 0x05, 0x75, 0x13, 0x42, 0x48, 0x0c, 0xfa, 0x01, 0xcb, 0x9d, 0xc4, 0x0b, 0x37, 0x71,
	0x83, 0xe8, 0xdf, 0x87, 0xc7, 0xb4, 0x04, 0xef, 0xde, 0x6d, 0xcf, 0x9e, 0x73, 0x78, 0xe1, 0x6a,
	0xc4, 0xa6, 0x1b, 0x50, 0x0d, 0xa3, 0x8f, 0x5e, 0xbe, 0xc2, 0xa5, 0xc6, 0x30, 0x78, 0x17, 0x90,
	0x73, 0x38, 0x6b, 0xbc, 0x45, 0x91, 0xe4, 0x49, 0x71, 0xae, 0x29, 0x73, 0x01, 0x17, 0x3d, 0x86,
	0x60, 0x5a, 0x14, 0xa7, 0x79, 0x52, 0x30, 0xbd, 0x1c, 0x27, 0xda, 0x9a, 0x68, 0xc4, 0x81, 0xae,
	0x29, 0xcb, 0x3b, 0xb8, 0xae, 0x5c, 0x3b, 0xa2, 0xed, 0xd0, 0xc5, 0xca, 0x7d, 0xfa, 0x89, 0x72,
	0xa6, 0x9f, 0x9d, 0x4c, 0x53, 0x96, 0x6f, 0xc0, 0x6a, 0xfc, 0xd2, 0xb4, 0xc6, 0x1e, 0xc0, 0x1f,
	0x00, 0xba, 0x55, 0x43, 0x73, 0xd3, 0x32, 0x53, 0x5b, 0xb3, 0xfe, 0x87, 0xc8, 0x1c, 0x60, 0xd6,
	0xd5, 0xd3, 0xf7, 0x1d, 0x65, 0xf9, 0x0e, 0xc7, 0xdf, 0x81, 0xb7, 0x70, 0x78, 0xb2, 0x96, 0x83,
	0x5a, 0x77, 0xb8, 0x61, 0x6a, 0xe9, 0x40, 0x9e, 0xf0, 0x7b, 0xc8, 0x5e, 0x30, 0xce, 0x2f, 0xcf,
	0xdf, 0x24, 0x4c, 0xd5, 0x9f, 0x7d, 0x03, 0x7f, 0x1c, 0xa9, 0xc5, 0xc7, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xed, 0x18, 0x43, 0x80, 0x55, 0x01, 0x00, 0x00,
}
