// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: recipe.proto

package recipe

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Recipe service

type RecipeService interface {
	Add(ctx context.Context, in *NewRecipe, opts ...client.CallOption) (*Response, error)
	GetRecipeByName(ctx context.Context, in *RecipeName, opts ...client.CallOption) (*RecipeInfo, error)
}

type recipeService struct {
	c    client.Client
	name string
}

func NewRecipeService(name string, c client.Client) RecipeService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "recipe"
	}
	return &recipeService{
		c:    c,
		name: name,
	}
}

func (c *recipeService) Add(ctx context.Context, in *NewRecipe, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Recipe.Add", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeService) GetRecipeByName(ctx context.Context, in *RecipeName, opts ...client.CallOption) (*RecipeInfo, error) {
	req := c.c.NewRequest(c.name, "Recipe.GetRecipeByName", in)
	out := new(RecipeInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Recipe service

type RecipeHandler interface {
	Add(context.Context, *NewRecipe, *Response) error
	GetRecipeByName(context.Context, *RecipeName, *RecipeInfo) error
}

func RegisterRecipeHandler(s server.Server, hdlr RecipeHandler, opts ...server.HandlerOption) error {
	type recipe interface {
		Add(ctx context.Context, in *NewRecipe, out *Response) error
		GetRecipeByName(ctx context.Context, in *RecipeName, out *RecipeInfo) error
	}
	type Recipe struct {
		recipe
	}
	h := &recipeHandler{hdlr}
	return s.Handle(s.NewHandler(&Recipe{h}, opts...))
}

type recipeHandler struct {
	RecipeHandler
}

func (h *recipeHandler) Add(ctx context.Context, in *NewRecipe, out *Response) error {
	return h.RecipeHandler.Add(ctx, in, out)
}

func (h *recipeHandler) GetRecipeByName(ctx context.Context, in *RecipeName, out *RecipeInfo) error {
	return h.RecipeHandler.GetRecipeByName(ctx, in, out)
}
